"""add language to posts

Revision ID: 128453485710
Revises: c6c3dafd04c3
Create Date: 2018-09-21 14:11:02.358789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128453485710'
down_revision = 'c6c3dafd04c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
